"use client";

import { useEffect, useMemo, useState } from "react";

const KICKOFF = new Date("2026-09-09T20:20:00-04:00");
const NAV = ["Home", "Draft", "Guide", "Coach"];
const COACH_TABS = ["Home", "Start/Sit", "Waivers", "Trades", "Lineup", "Watch", "Analysts", "League"];
const POSITIONS = ["ALL", "QB", "RB", "WR", "TE"];
const SLOT = {0:"QB",2:"RB",4:"WR",6:"TE",16:"DST",17:"K",20:"BE",21:"IR",23:"FLEX"};

const fmt=(value,digits=1,suffix="")=>value===null||value===undefined||Number.isNaN(Number(value))?"—":`${Number(value).toFixed(digits)}${suffix}`;
function clockText(){const total=Math.max(0,Math.floor((KICKOFF.getTime()-Date.now())/1000));if(!total)return"LIVE";const d=Math.floor(total/86400),h=Math.floor(total%86400/3600),m=Math.floor(total%3600/60),s=total%60,t=(v)=>String(v).padStart(2,"0");return`${t(d)}D ${t(h)}H ${t(m)}M ${t(s)}S`;}
function teamForPick(pick,teams){const round=Math.floor((pick-1)/teams)+1,within=(pick-1)%teams+1;return round%2?within:teams-within+1;}
function articleDate(value){if(!value)return"ESPN";const d=new Date(value);return Number.isNaN(d.getTime())?"ESPN":d.toLocaleDateString("en-US",{month:"short",day:"numeric"});}

function PillRow({values,value,onChange,className=""}){return <div className={`pill-row ${className}`} role="tablist">{values.map((item)=><button key={item} type="button" className={`pill ${value===item?"active":""}`} onClick={()=>onChange(item)} aria-pressed={value===item}>{item}</button>)}</div>;}
function PlayerSelect({label,players,value,onChange}){return <label className="field"><span>{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)}>{players.map((p)=><option key={p.name} value={p.name}>{p.name} — {p.pos} {p.team}</option>)}</select></label>;}
function MetricCard({item,winner}){return <div className={`evidence-card ${winner?"winner":""}`}><div className="evidence-name"><div><b>{item.name}</b><span>{item.pos} · {item.team}</span></div><strong>#{item.rank??"—"}</strong></div><div className="metric-grid"><div><b>{fmt(item.floor)}</b><span>Floor</span></div><div><b>{fmt(item.ppg)}</b><span>PPG</span></div><div><b>{fmt(item.ceiling)}</b><span>Ceiling</span></div><div><b>{fmt(item.rate15,0,"%")}</b><span>15+ Weeks</span></div></div></div>;}
function ScreenHead({kicker,title,copy}){return <div className="screen-head"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{copy}</p></div>;}

export default function ShivaApp(){
  const [splash,setSplash]=useState(true),[page,setPage]=useState("Home"),[clock,setClock]=useState(clockText()),[players,setPlayers]=useState([]),[error,setError]=useState("");
  useEffect(()=>{const t=window.setTimeout(()=>setSplash(false),2200);return()=>clearTimeout(t);},[]);
  useEffect(()=>{const tick=()=>setClock(clockText());tick();const t=setInterval(tick,1000);return()=>clearInterval(t);},[]);
  useEffect(()=>{let live=true;fetch("/api/players").then((r)=>{if(!r.ok)throw new Error("Player rankings unavailable.");return r.json();}).then((d)=>live&&setPlayers(d.players||[])).catch((e)=>live&&setError(e.message));return()=>{live=false;};},[]);
  return <main className="app-shell">
    {splash&&<div className="splash"><img src="/shiva-trophy.png" alt="THE SHIVA trophy" fetchPriority="high"/></div>}
    <header className="topbar">
      <div className="brand"><img className="brand-trophy" src="/shiva-trophy.png" alt=""/><div className="brand-copy"><div className="brand-title">Shiva</div><div className="brand-subtitle">Fantasy Football Intelligence</div></div></div>
      {page==="Home"&&<div className="kickoff-clock" aria-label={`NFL kickoff countdown ${clock}`}><span>NFL KICKOFF</span><b>{clock}</b></div>}
    </header>
    <div className="content">{error&&<div className="notice error">{error}</div>}{page==="Home"&&<Home go={setPage}/>} {page==="Draft"&&<Draft players={players}/>} {page==="Guide"&&<Guide players={players}/>} {page==="Players"&&<Players players={players}/>} {page==="Coach"&&<Coach players={players}/>}</div>
    <nav className="bottom-nav" aria-label="Primary navigation">{NAV.map((item)=><button key={item} type="button" className={page===item?"active":""} onClick={()=>setPage(item)}><span className="nav-icon">{item==="Home"?"⌂":item==="Draft"?"◫":item==="Guide"?"▤":"✦"}</span><span>{item}</span></button>)}</nav>
  </main>;
}

function Home({go}){
  const [edge,setEdge]=useState(null),[edgeError,setEdgeError]=useState(""),[edgeMode,setEdgeMode]=useState(""),[news,setNews]=useState([]),[newsError,setNewsError]=useState("");
  useEffect(()=>{let live=true;fetch("/api/edge").then((r)=>{if(!r.ok)throw new Error("Verified Shiva Edge evidence is temporarily unavailable.");return r.json();}).then((d)=>live&&setEdge(d)).catch((e)=>live&&setEdgeError(e.message));fetch("/api/espn?action=news").then((r)=>{if(!r.ok)throw new Error("Current ESPN news is temporarily unavailable.");return r.json();}).then((d)=>live&&setNews((d.articles||[]).slice(0,6))).catch((e)=>live&&setNewsError(e.message));return()=>{live=false;};},[]);
  const floor=edge?.floor||[],ceiling=edge?.ceiling||[],active=edgeMode==="floor"?floor:ceiling,activeStat=edgeMode==="floor"?"rate15":"boom25";
  return <section className="home-screen">
    <div className="home-actions"><button onClick={()=>go("Draft")}>◫ <span>Draft</span></button><button onClick={()=>go("Coach")}>✦ <span>Coach</span></button><button onClick={()=>go("Guide")}>▤ <span>Guide</span></button><button onClick={()=>go("Players")}>👥 <span>Players</span></button></div>

    <div className="home-section-title">The Shiva Edge</div><div className="home-section-subtitle">Historical evidence, not a mystery score.</div>
    <div className="edge-preview-grid">
      <div className={`edge-preview-card ${edgeMode==="floor"?"active":""}`}><div className="edge-preview-kicker">Raise the floor</div><div className="edge-preview-copy">Consistent 15+ scoring</div>{floor[0]?<div className="edge-preview-leader"><div><b>{floor[0].name}</b><span>{floor[0].pos} · {floor[0].team}</span></div><strong>{fmt(floor[0].rate15,0,"%")}</strong></div>:<div className="edge-preview-loading">Verified 2025 evidence loading…</div>}<button type="button" onClick={()=>setEdgeMode(edgeMode==="floor"?"":"floor")}>Floor Rankings →</button></div>
      <div className={`edge-preview-card ${edgeMode==="ceiling"?"active":""}`}><div className="edge-preview-kicker">Keep the ceiling</div><div className="edge-preview-copy">Week-winning upside</div>{ceiling[0]?<div className="edge-preview-leader"><div><b>{ceiling[0].name}</b><span>{ceiling[0].pos} · {ceiling[0].team}</span></div><strong>{fmt(ceiling[0].boom25,0,"%")}</strong></div>:<div className="edge-preview-loading">Verified 2025 evidence loading…</div>}<button type="button" onClick={()=>setEdgeMode(edgeMode==="ceiling"?"":"ceiling")}>Ceiling Rankings →</button></div>
    </div>
    {edgeError&&<div className="notice error">{edgeError}</div>}
    {edgeMode&&active.length>0&&<div className="edge-panel"><span>{edgeMode==="floor"?"FLOOR RANKINGS":"CEILING RANKINGS"}</span><h2>{edgeMode==="floor"?"Most repeatable 15+ point weeks":"Most frequent 25+ point explosions"}</h2><p>Verified 2025 ESPN full-PPR weekly results. Minimum eight games; PPG breaks ties.</p>{active.map((p,i)=><div className="edge-rank-row" key={p.name}><em>#{i+1}</em><div><b>{p.name}</b><small>{p.pos} · {p.team} · {fmt(p.ppg)} PPG</small></div><strong>{fmt(p[activeStat],0,"%")}</strong></div>)}</div>}

    <div className="home-section-title blast-title">Shiva Blast</div><div className="home-section-subtitle">Current ESPN fantasy/NFL context with the article image and the actual story link.</div>
    {newsError&&<div className="notice error">{newsError}</div>}
    {!newsError&&!news.length&&<div className="news-empty">Loading current verified ESPN news…</div>}
    <div className="news-grid">{news.map((article,i)=><a className="news-card" href={article.url||"#"} target="_blank" rel="noreferrer" key={`${article.headline}-${i}`}>{article.image?<img className="news-image" src={article.image} alt="" loading="lazy"/>:<div className="news-image placeholder"/>}<div className="news-body"><span>{articleDate(article.published)} · ESPN</span><b>{article.headline}</b><p>{article.description}</p><em>Read story →</em></div></a>)}</div>
  </section>;
}

function Draft({players}){
  const teams=10; const [slot,setSlot]=useState(1),[started,setStarted]=useState(false),[drafted,setDrafted]=useState([]),[pos,setPos]=useState("ALL");
  const taken=useMemo(()=>new Set(drafted.map((d)=>d.player.name)),[drafted]),available=players.filter((p)=>!taken.has(p.name)),board=available.filter((p)=>pos==="ALL"||p.pos===pos).slice(0,34),next=drafted.length+1,onClock=started&&teamForPick(next,teams)===slot;
  const sim=(seed)=>{const copy=[...seed];while(copy.length<150){const pick=copy.length+1;if(teamForPick(pick,teams)===slot)break;const used=new Set(copy.map((d)=>d.player.name)),p=players.find((x)=>!used.has(x.name));if(!p)break;copy.push({pick,team:teamForPick(pick,teams),player:p});}return copy;};
  const start=()=>{setDrafted(sim([]));setStarted(true);};
  const choose=(player)=>{if(!onClock)return;const after=[...drafted,{pick:next,team:slot,player}];setDrafted(sim(after));};
  if(!started)return <section><ScreenHead kicker="DRAFT ROOM" title="Mock Draft" copy="Choose your slot and start the room. Shiva handles the snake order and keeps the board in current-rank context."/><div className="draft-start-card"><b>Start a Mock Draft</b><p>Nothing goes on the clock until you start it.</p><label className="field"><span>Your draft position</span><select value={slot} onChange={(e)=>setSlot(Number(e.target.value))}>{Array.from({length:teams},(_,i)=>i+1).map((n)=><option key={n} value={n}>Pick #{n}</option>)}</select></label><button className="primary-cta" onClick={start}>Start Mock Draft</button></div></section>;
  return <section><ScreenHead kicker="DRAFT ROOM" title="Mock Draft" copy="Current board, snake order and your roster decisions in one screen."/><div className="draft-status"><div><span>Pick</span><b>{next}</b></div><div><span>Round</span><b>{Math.floor((next-1)/teams)+1}</b></div><div><span>Your Slot</span><b>#{slot}</b></div></div><div className={`on-clock ${onClock?"live":""}`}>{onClock?"YOU’RE ON THE CLOCK":"Simulating managers between your picks"}</div><PillRow values={POSITIONS} value={pos} onChange={setPos}/><div className="draft-board">{board.map((p)=><button key={p.name} type="button" className="draft-player" onClick={()=>choose(p)} disabled={!onClock}><div><b>{p.name}</b><span>{p.pos} · {p.team} · Bye {p.bye??"—"}</span></div><div><strong>#{p.overallRank}</strong><small>ADP {fmt(p.adp)}</small></div></button>)}</div><button className="secondary-action" onClick={()=>{setStarted(false);setDrafted([]);}}>Reset Draft</button></section>;
}

function Guide({players}){const [pos,setPos]=useState("ALL"),[section,setSection]=useState("Rankings");const filtered=players.filter((p)=>pos==="ALL"||p.pos===pos).slice(0,55);return <section><ScreenHead kicker="2026 DRAFT GUIDE" title="Build a better draft." copy="Rankings, roster construction and decision rules designed for full-PPR formats."/><PillRow values={["Rankings","Strategy","Targets","Rules"]} value={section} onChange={setSection} className="guide-section-pills"/>{section==="Rankings"&&<><div className="section-heading"><h2>Rankings</h2><p>Filter by position. The selected pill itself is the only indicator.</p></div><PillRow values={POSITIONS} value={pos} onChange={setPos}/><div className="ranking-list">{filtered.map((p)=><div className="ranking-row" key={p.name}><span className="ranking-number">{p.overallRank}</span><span className="pos-chip">{p.pos}</span><div><b>{p.name}</b><small>{p.team} · Bye {p.bye??"—"}</small></div><strong>ADP {fmt(p.adp)}</strong></div>)}</div></>}{section==="Strategy"&&<div className="guide-grid"><GuideCard title="Rounds 1–3" copy="Prioritize elite workload and target volume. Avoid paying a premium for replaceable production."/><GuideCard title="Rounds 4–7" copy="Attack falling tiers before positional runs force you into bad value."/><GuideCard title="Rounds 8–11" copy="Build contingency value: ambiguous backfields, ascending receivers and high-route tight ends."/><GuideCard title="Late rounds" copy="Chase paths to relevance. Bench spots should create leverage, not comfort."/></div>}{section==="Targets"&&<div className="guide-grid">{players.slice(0,8).map((p)=><GuideCard key={p.name} title={p.name} copy={`${p.pos} · ${p.team} · current overall rank #${p.overallRank} · ADP ${fmt(p.adp)}`}/>)}</div>}{section==="Rules"&&<div className="article-body"><h2>Shiva rules</h2><p><b>Raise the floor:</b> favor players who repeatedly create startable weeks.</p><p><b>Keep the ceiling:</b> preserve enough explosive outcomes to win high-scoring matchups.</p><p><b>Draft the room:</b> roster construction between your picks changes what is actually scarce.</p><p><b>Separate facts from projections:</b> historical evidence and current rankings are shown as different inputs.</p></div>}</section>;}
function GuideCard({title,copy}){return <div className="guide-card"><b>{title}</b><p>{copy}</p></div>;}

function Players({players}){const [pos,setPos]=useState("ALL"),[query,setQuery]=useState("");const filtered=players.filter((p)=>(pos==="ALL"||p.pos===pos)&&(!query||p.name.toLowerCase().includes(query.toLowerCase())||p.team.toLowerCase().includes(query.toLowerCase()))).slice(0,100);return <section><ScreenHead kicker="PLAYER BOARD" title="Players" copy="Current-season ranking context from Shiva's verified rankings dataset."/><label className="field"><span>Search players</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Name or team"/></label><PillRow values={POSITIONS} value={pos} onChange={setPos}/><div className="ranking-list">{filtered.map((p)=><div className="ranking-row" key={p.name}><span className="ranking-number">{p.overallRank}</span><span className="pos-chip">{p.pos}</span><div><b>{p.name}</b><small>{p.team} · Bye {p.bye??"—"}</small></div><strong>ADP {fmt(p.adp)}</strong></div>)}</div></section>;}

function Coach({players}){const [tab,setTab]=useState("Home"),[league,setLeague]=useState(null);return <section><ScreenHead kicker="SHIVA COACH" title="Make the decision. See the why." copy="Readable, evidence-first tools for start/sit, waivers, trades, lineup checks and league context."/><PillRow values={COACH_TABS} value={tab} onChange={setTab} className="coach-tabs"/><div className="coach-hero"><span>SHIVA SAYS</span><h2>{tab==="Home"?"Your command center":tab==="Start/Sit"?"Start / Sit":tab==="Waivers"?"Waiver Wire":tab==="Trades"?"Trade Analyzer":tab}</h2><p>{tab==="Home"?"Fast decisions, clear evidence, no fake confidence numbers.":"Current rankings and verified historical scoring stay separate so the recommendation is explainable."}</p></div>{tab==="Home"&&<CoachHome league={league}/>} {tab==="Start/Sit"&&<StartSit players={players}/>} {tab==="Waivers"&&<Waivers players={players} league={league}/>} {tab==="Trades"&&<Trades players={players}/>} {tab==="Lineup"&&<Lineup players={players}/>} {tab==="Watch"&&<Watch players={players}/>} {tab==="Analysts"&&<Analysts/>} {tab==="League"&&<League league={league} setLeague={setLeague}/>}</section>;}
function CoachHome({league}){return <div className="coach-grid"><div className="coach-card"><span>LINEUP EDGE</span><b>Thursday FLEX protection</b><p>Keep early-week players out of FLEX so Sunday replacement options stay open.</p></div><div className="coach-card"><span>DRAFT EDGE</span><b>Read the managers between picks</b><p>Use roster construction around the turn instead of blindly following ADP.</p></div><div className="coach-card"><span>TEAM BUILD</span><b>Raise the floor</b><p>Repeatable 15+ point weeks keep you alive in bad matchup environments.</p></div><div className="coach-card"><span>LEAGUE</span><b>{league?league.name:"ESPN not connected"}</b><p>{league?`${league.teams.length} teams · scoring period ${league.scoringPeriod??"—"}`:"Connect your ESPN league for roster-aware context."}</p></div></div>;}

function useEvidence(names){const [state,setState]=useState({loading:false,data:null,error:""});useEffect(()=>{if(!names.length||names.some((n)=>!n)){setState({loading:false,data:null,error:""});return;}let live=true;setState({loading:true,data:null,error:""});fetch(`/api/coach?players=${encodeURIComponent(names.join("|"))}`).then((r)=>{if(!r.ok)throw new Error("Evidence lookup failed.");return r.json();}).then((d)=>live&&setState({loading:false,data:d,error:""})).catch((e)=>live&&setState({loading:false,data:null,error:e.message}));return()=>{live=false;};},[names.join("|")]);return state;}
function StartSit({players}){const [a,setA]=useState(players[0]?.name||""),[b,setB]=useState(players[1]?.name||"");useEffect(()=>{if(!a&&players[0])setA(players[0].name);if(!b&&players[1])setB(players[1].name);},[players,a,b]);const result=useEvidence(a&&b&&a!==b?[a,b]:[]);return <div><div className="two-fields"><PlayerSelect label="Player A" players={players} value={a} onChange={setA}/><PlayerSelect label="Player B" players={players} value={b} onChange={setB}/></div>{a===b&&<div className="notice">Choose two different players.</div>}{result.loading&&<div className="notice">Loading verified scoring evidence…</div>}{result.error&&<div className="notice error">{result.error}</div>}{result.data&&<><div className="shiva-call"><span>SHIVA SAYS</span><b>Start {result.data.recommendation}</b><p>Based on the strongest verified mix of weekly floor, scoring average, ceiling, consistency and current ranking context.</p></div><div className="evidence-grid">{result.data.evidence.map((e)=><MetricCard key={e.name} item={e} winner={e.name===result.data.recommendation}/>)}</div><div className="data-note">Historical source: {result.data.source}. Scoring: {result.data.scoring}. This is not a fabricated weekly projection.</div></>}</div>;}
function Waivers({players,league}){const roster=new Set((league?.teams||[]).flatMap((t)=>t.roster||[]).map((r)=>r.player));const options=players.filter((p)=>!roster.has(p.name)).slice(0,30);return <div><div className="section-heading"><h2>Best available profiles</h2><p>{league?"Players already rostered in the connected league are excluded from this board.":"Connect ESPN to make this board roster-aware. Until then, this is current rank context only."}</p></div><div className="ranking-list">{options.map((p)=><div className="ranking-row" key={p.name}><span className="ranking-number">{p.overallRank}</span><span className="pos-chip">{p.pos}</span><div><b>{p.name}</b><small>{p.team} · Bye {p.bye??"—"}</small></div><strong>ADP {fmt(p.adp)}</strong></div>)}</div></div>;}
function Trades({players}){const seed=players.slice(0,4),[mineA,setMineA]=useState(seed[0]?.name||""),[mineB,setMineB]=useState(seed[1]?.name||""),[theirA,setTheirA]=useState(seed[2]?.name||""),[theirB,setTheirB]=useState(seed[3]?.name||"");useEffect(()=>{if(!mineA&&players[0]){setMineA(players[0].name);setMineB(players[1]?.name||players[0].name);setTheirA(players[2]?.name||players[0].name);setTheirB(players[3]?.name||players[1]?.name||players[0].name);}},[players,mineA]);const result=useEvidence([mineA,mineB,theirA,theirB].filter(Boolean));let receive=null,give=null;if(result.data){const map=new Map(result.data.evidence.map((e)=>[e.name,e]));const s=(n)=>map.get(n)?.evidenceScore||0;give=s(mineA)+s(mineB);receive=s(theirA)+s(theirB);}return <div><div className="trade-grid"><div><h3>You give</h3><PlayerSelect label="Player 1" players={players} value={mineA} onChange={setMineA}/><PlayerSelect label="Player 2" players={players} value={mineB} onChange={setMineB}/></div><div><h3>You receive</h3><PlayerSelect label="Player 1" players={players} value={theirA} onChange={setTheirA}/><PlayerSelect label="Player 2" players={players} value={theirB} onChange={setTheirB}/></div></div>{result.loading&&<div className="notice">Comparing verified evidence…</div>}{result.data&&<div className="shiva-call"><span>SHIVA SAYS</span><b>{receive>=give?"Receive side has the stronger evidence profile":"Keep your current side"}</b><p>Package comparison uses the same floor-first historical evidence score and current rank context. It is not a fake universal trade-value chart.</p></div>}</div>;}
function Lineup({players}){const [name,setName]=useState(players[0]?.name||""),[game,setGame]=useState(null),[error,setError]=useState("");useEffect(()=>{if(!name&&players[0])setName(players[0].name);},[players,name]);const check=async()=>{setError("");const p=players.find((x)=>x.name===name);try{const r=await fetch("/api/espn?action=scoreboard"),d=await r.json();if(!r.ok)throw new Error(d.error||"Schedule unavailable.");let found=null;for(const ev of d.events||[]){const comp=ev.competitions?.[0],teams=comp?.competitors||[],me=teams.find((c)=>c.team?.abbreviation===p?.team);if(me){found={day:new Date(ev.date).toLocaleDateString("en-US",{weekday:"long"}),event:ev.shortName||ev.name};break;}}setGame(found||{day:null,event:"No current scoreboard game found."});}catch(e){setError(e.message);}};return <div><PlayerSelect label="Player currently in FLEX" players={players} value={name} onChange={setName}/><button className="primary-cta compact" onClick={check}>Check lineup edge</button>{error&&<div className="notice error">{error}</div>}{game&&<div className={`shiva-call ${game.day==="Thursday"?"danger":""}`}><span>LINEUP CHECK</span><b>{game.day==="Thursday"?`Move ${name} out of FLEX`:"No Thursday FLEX trap detected"}</b><p>{game.day?`${game.event} is scheduled for ${game.day}.`:game.event}</p></div>}</div>;}
function Watch({players}){const [name,setName]=useState(players[0]?.name||""),[articles,setArticles]=useState([]),[loading,setLoading]=useState(false);useEffect(()=>{if(!name&&players[0])setName(players[0].name);},[players,name]);const run=async()=>{setLoading(true);try{const r=await fetch(`/api/espn?action=news&player=${encodeURIComponent(name)}`),d=await r.json();setArticles(d.articles||[]);}finally{setLoading(false);}};return <div><PlayerSelect label="Watch player" players={players} value={name} onChange={setName}/><button className="primary-cta compact" onClick={run}>Check ESPN context</button>{loading&&<div className="notice">Checking ESPN…</div>}<div className="watch-list">{articles.map((a,i)=><a className="watch-card" href={a.url||"#"} target="_blank" rel="noreferrer" key={`${a.headline}-${i}`}><span>ESPN</span><b>{a.headline}</b><p>{a.description}</p></a>)}</div></div>;}
function Analysts(){const [report,setReport]=useState(null);const upload=(e)=>{const file=e.target.files?.[0];if(!file)return;file.text().then((text)=>{const [head,...rows]=text.trim().split(/\r?\n/),cols=(head||"").split(",").map((x)=>x.trim().toLowerCase()),required=["analyst","player","rank","season","week"],missing=required.filter((x)=>!cols.includes(x));setReport(missing.length?{ok:false,text:`Missing required columns: ${missing.join(", ")}`}:{ok:true,text:`Validated ${rows.length} ranking rows. The file has the required analyst, player, rank, season and week fields.`});});};return <div><div className="section-heading"><h2>Analyst Tracker</h2><p>Upload a weekly rankings snapshot. Shiva validates the structure before any historical grading is attempted.</p></div><label className="upload"><span>Upload rankings CSV</span><input type="file" accept=".csv,text/csv" onChange={upload}/></label>{report&&<div className={`notice ${report.ok?"":"error"}`}>{report.text}</div>}<div className="data-note">Required columns: analyst, player, rank, season, week. Optional: position. No analyst score is shown until rows are matched to verified historical outcomes.</div></div>;}
function League({league,setLeague}){const [leagueId,setLeagueId]=useState(""),[season,setSeason]=useState(2026),[swid,setSwid]=useState(""),[espnS2,setEspnS2]=useState(""),[status,setStatus]=useState("");const connect=async()=>{setStatus("Connecting…");try{const r=await fetch("/api/espn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leagueId,season,swid,espnS2})}),d=await r.json();if(!r.ok)throw new Error(d.error||"ESPN connection failed.");setLeague(d.league);setStatus("");}catch(e){setStatus(e.message);}};if(league)return <div><div className="league-connected"><span>ESPN LEAGUE CONNECTED</span><b>{league.name}</b><p>{league.season} · {league.teams.length} teams · scoring period {league.scoringPeriod??"—"}</p></div><div className="team-list">{league.teams.map((t)=><div className="team-card" key={t.id}><b>{t.name}</b><span>{t.wins??"—"}-{t.losses??"—"}</span><small>{(t.roster||[]).filter((r)=>SLOT[r.lineupSlotId]!=="BE").slice(0,8).map((r)=>r.player).filter(Boolean).join(" · ")}</small></div>)}</div><button className="secondary-action" onClick={()=>setLeague(null)}>Disconnect league</button></div>;return <div><div className="two-fields"><label className="field"><span>ESPN League ID</span><input value={leagueId} onChange={(e)=>setLeagueId(e.target.value)} inputMode="numeric"/></label><label className="field"><span>Season</span><input value={season} onChange={(e)=>setSeason(Number(e.target.value))} inputMode="numeric"/></label></div><details><summary>Private league credentials</summary><div className="two-fields"><label className="field"><span>SWID</span><input type="password" value={swid} onChange={(e)=>setSwid(e.target.value)}/></label><label className="field"><span>espn_s2</span><input type="password" value={espnS2} onChange={(e)=>setEspnS2(e.target.value)}/></label></div></details><button className="primary-cta compact" onClick={connect}>Connect ESPN league</button>{status&&<div className={`notice ${status==="Connecting…"?"":"error"}`}>{status}</div>}<div className="data-note">Credentials are submitted directly to the server route for the connection request and are not written to the repository.</div></div>;}
